input.onPinPressed(TouchPin.P0, function () {
    led.plot(2, 0)
    led.plot(1, 1)
    led.plot(0, 2)
    led.plot(1, 3)
    led.plot(2, 4)
    led.plot(3, 3)
    led.plot(4, 2)
    led.plot(3, 1)
    basic.pause(2000)
    led.unplot(2, 0)
    led.unplot(1, 1)
    led.unplot(0, 2)
    led.unplot(1, 3)
    led.unplot(2, 4)
    led.unplot(3, 3)
    led.unplot(4, 2)
    led.unplot(3, 1)
})
input.onPinPressed(TouchPin.P2, function () {
    led.plot(2, 0)
    led.plot(1, 1)
    led.plot(0, 2)
    led.plot(1, 3)
    led.plot(2, 4)
    led.plot(3, 3)
    led.plot(4, 2)
    led.plot(3, 1)
    basic.pause(2000)
    led.unplot(2, 0)
    led.unplot(1, 1)
    led.unplot(0, 2)
    led.unplot(1, 3)
    led.unplot(2, 4)
    led.unplot(3, 3)
    led.unplot(4, 2)
    led.unplot(3, 1)
})
input.onButtonPressed(Button.AB, function () {
    led.plot(0, 2)
    led.plot(2, 0)
    led.plot(4, 2)
    led.plot(1, 1)
    led.plot(1, 2)
    led.plot(2, 2)
    led.plot(3, 1)
    led.plot(3, 2)
    basic.pause(2000)
    led.unplot(0, 2)
    led.unplot(2, 0)
    led.unplot(4, 2)
    led.unplot(1, 1)
    led.unplot(1, 2)
    led.unplot(2, 2)
    led.unplot(2, 1)
    led.unplot(3, 1)
    led.unplot(3, 2)
})
input.onPinPressed(TouchPin.P1, function () {
    led.plot(0, 1)
    led.plot(0, 2)
    led.plot(0, 2)
    led.plot(1, 1)
    led.plot(0, 2)
    led.plot(0, 3)
    led.plot(4, 2)
    led.plot(3, 1)
    basic.pause(2000)
    led.unplot(2, 0)
    led.unplot(1, 1)
    led.unplot(0, 2)
    led.unplot(1, 3)
    led.unplot(2, 4)
    led.unplot(3, 3)
    led.unplot(4, 2)
    led.unplot(3, 1)
})
